### ISSUE TITLE
ntpq is broken on latest bloody

### ISSUE THREAD

**Issue by sjorge** [omniosorg/omnios-build#2411]
```
root@jupiter:~# ntpq -p
Traceback (most recent call last):
  File "/usr/bin/ntpq", line 26, in <module>
    import ntp.ntpc
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 56, in <module>
    _ntpc = _importado()
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 38, in _importado
    return _dlo(ntpc_paths)
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 53, in _dlo
    raise OSError("Can't find %s library" % LIB)
OSError: Can't find ntpc library
```

Was working fine before last bloody update

**Comment by sjorge** [comment]
Edit, ntpdate is also broken

```
root@jupiter:~# ntpdate ntp.acheron.be
Traceback (most recent call last):
  File "/usr/bin/ntpdig", line 19, in <module>
    import ntp.packet
  File "/usr/lib/python3.9/vendor-packages/ntp/packet.py", line 219, in <module>
    import ntp.ntpc
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 56, in <module>
    _ntpc = _importado()
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 38, in _importado
    return _dlo(ntpc_paths)
  File "/usr/lib/python3.9/vendor-packages/ntp/ntpc.py", line 53, in _dlo
    raise OSError("Can't find %s library" % LIB)
OSError: Can't find ntpc library
```

**Comment by citrus-it** [comment]
Somehow, the .so file has moved between ntpsec versions 1.2.0 and 1.2.1

```diff
bloody:omnios.bloody:% pkgdiff -i hash -i chash -i pkg.content-hash -i pkg.csize -i pkg.size -i timestamp -i elfhash old new
set name=pkg.human-version
  - value=1.2.0
  + value=1.2.1
+ link path=usr/lib/python3.9/vendor-packages/libntpc.so target=libntpc.so.1.1.0
+ link path=usr/lib/python3.9/vendor-packages/libntpc.so.1 target=libntpc.so.1.1.0
+ file path=usr/lib/python3.9/vendor-packages/libntpc.so.1.1.0
- link path=usr/lib/python3.9/vendor-packages/ntp/libntpc.so target=libntpc.so.1.1.0
- link path=usr/lib/python3.9/vendor-packages/ntp/libntpc.so.1 target=libntpc.so.1.1.0
- file path=usr/lib/python3.9/vendor-packages/ntp/libntpc.so.1.1.0
```
