### ISSUE TITLE
/usr/lib/smbsrv/smbd dumping core on startup

### ISSUE THREAD

**Issue by discard-this** [omniosorg/omnios-build#2441]
Host is running 151038. SMB services suddenly stopped. In debugging the problem I see the following in /var/svc/log/network-smb-server:default.log:

> [ Aug 12 06:30:35 Executing start method ("/usr/lib/smbsrv/smbd start"). ]
> smbd: smbd starting, pid 22478
> smbd: NetBIOS services disabled
> smbd: service initialized
> [ Aug 12 06:30:35 Method "start" exited with status 0. ]
> smbd_dc_monitor: online
> smbd_localtime_monitor: online
> @ Thu Aug 12 06:30:46 2021
> smbd.info: smbd_dc_update: [redacted]: located [redacted]
> [ Aug 12 06:31:46 Stopping because process dumped core. ]
> [ Aug 12 06:31:46 Executing stop method (:kill). ]

This was followed by multiple retry attempts - all with the same result - then ultimately giving up since the service was restarting too frequently.

I had to get things working again quickly so rebooted the host and it has been stable for the past hour.

**Comment by discard-this** [comment]
**Probably** not related, but the logs are full of the same complaint as noted in https://illumos.topicbox.com/groups/omnios-discuss/T4ef0de18d0619eef-Mb0f120c2a79f9943ee6d53e5/smbd572-cant-get-sid-for-id0-type0-status-9977

> Aug 11 19:03:23 fs2 smbd[25660]: [ID 617204 daemon.error] Can't get SID for ID=0 type=0, status=-9977
> Aug 11 19:10:05 fs2 smbd[25660]: [ID 617204 daemon.error] Can't get SID for ID=0 type=0, status=-9977
> Aug 11 19:16:48 fs2 smbd[25660]: [ID 617204 daemon.error] Can't get SID for ID=0 type=0, status=-9977
> Aug 11 19:23:30 fs2 smbd[25660]: [ID 617204 daemon.error] Can't get SID for ID=0 type=0, status=-9977
> Aug 11 19:30:13 fs2 smbd[25660]: [ID 617204 daemon.error] Can't get SID for ID=0 type=0, status=-9977

Before and after the events.

**Comment by discard-this** [comment]
If I can find the core file, sure...

**Comment by discard-this** [comment]
[core.smbd.1628737077.zip](https://github.com/omniosorg/omnios-build/files/6976683/core.smbd.1628737077.zip)

I've preserved the others as well but when I tried to upload a zip'd tarfile the system didn't like it. Let me know if you want more of them.

**Comment by discard-this** [comment]
Additional data: It looks like one of our DCs (dc1) patched and rebooted around the time this problem first happened last night. We have multiple DCs and they're all correctly entered in DNS so the SMB service **should** have just moved from talking with dc1 to dc2.

**Comment by danmcd** [comment]
Hmmmm... interesting:

```
smartos-build(~/cores/nomad-smbd)[0]% mdb core.smbd.1628737077
Loading modules: [ libumem.so.1 libc.so.1 libuutil.so.1 libcmdutils.so.1 libmlsvc.so.1 libavl.so.1 libtopo.so.1 libnvpair.so.1 ld.so.1 ]
> $C
fe7d0ab8 libc.so.1`syscall+0x13(feee9204, 1c, fe7d0a9c, 0, fe7d0b08, 26)
fe7d0ad8 0xfee6d77f(fe7d0b44, 1, 1388, bd01001a, 0, 400726)
fe7d0b08 smbd_dc_update(fe7d0b44, 8071bcc, fe7d0b3c, 805abd4)
fe7d0fc8 smbd_dc_monitor+0x144(0, 0, 0, 0)
fe7d0fe8 libc.so.1`_thrp_setup+0x81(fec51a40)
fe7d0ff8 libc.so.1`_lwp_start(fec51a40, 0, 0, 0, 0, 0)
> ::status
debugging core file of smbd (32-bit) from fs2
initial argv: /usr/lib/smbsrv/smbd start
threading model: native threads
status: process panicked
upanic message: *** stack smashing detected
> 
```

**Comment by citrus-it** [comment]
Just to fill in the missing pieces

```
(gdb) where
#0  0xfeedef53 in syscall () from /lib/libc.so.1
#1  0xfeedd59a in upanic () from /lib/libc.so.1
#2  0xfee6d77f in __stack_chk_fail () from /lib/libc.so.1
#3  0x0805aa66 in smbd_dc_check ()
#4  0x0805acc7 in smbd_dc_monitor ()
#5  0xfeed8031 in _thrp_setup () from /lib/libc.so.1
#6  0xfeed82e0 in ?? () from /lib/libc.so.1
#7  0x00000000 in ?? ()
```

**Comment by citrus-it** [comment]
I've opened https://www.illumos.org/issues/14021 and this is being tracked there too.
