### ISSUE TITLE
pkg broken after update on OmniOS r151046

### ISSUE THREAD

**Issue by jclulow** [omniosorg/omnios-build#3770]
I updated **pkg** and then it stopped working:

```
gerrit0 # pkg update -v pkg
            Packages to update:         4
            Services to change:         1
     Estimated space available:  12.02 GB
Estimated space to be consumed: 266.95 MB
       Create boot environment:        No
Create backup boot environment:       Yes
          Rebuild boot archive:        No

Changed packages:
omnios
  library/security/openssl-3
    3.0.12-151046.0 -> 3.0.15-151046.0
  package/pkg
    0.5.11-151046.0:20231010T121712Z -> 0.5.11-151046.0:20240930T114651Z
  runtime/python-311
    3.11.5-151046.0 -> 3.11.11-151046.0
  web/curl
    8.5.0-151046.0 -> 8.11.1-151046.0

Services:
  restart_fmri:
    svc:/system/update-man-index:default

Building new search index                    425/425
DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
library/security/openssl-3               0/4        0/4844     0.0/48.1      --

Completed                                4/4     4844/4844    48.1/48.1  200k/s

PHASE                                          ITEMS
Removing old actions                         204/204
Installing new actions                       501/501
Updating modified actions                  5358/5358
Updating package state database                 Done
Updating package cache                           4/4
Updating image state                            Done
Creating fast lookup database                   Done
Reading search index                            Done
Updating search index                            4/4
Updating package cache                           2/2
gerrit0 #
gerrit0 # pkg update -nv
Traceback (most recent call last):
  File "/usr/bin/pkg", line 89, in <module>
    import pkg.actions as actions
  File "/usr/lib/python3.11/vendor-packages/pkg/actions/__init__.py", line 67, in <module>
    module = __import__("{0}.{1}".format(__name__, modname),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/vendor-packages/pkg/actions/hardlink.py", line 33, in <module>
    from . import generic, link
  File "/usr/lib/python3.11/vendor-packages/pkg/actions/generic.py", line 46, in <module>
    import pkg.client.api_errors as apx
  File "/usr/lib/python3.11/vendor-packages/pkg/client/api_errors.py", line 32, in <module>
    import xml.parsers.expat as expat
  File "/usr/lib/python3.11/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: ld.so.1: python3.11: fatal: relocation error: file /usr/lib/python3.11/lib-dynload/pyexpat.cpython-311.so: symbol XML_SetReparseDeferralEnabled: referenced symbol not found
```

**Comment by jclulow** [comment]
It would appear that the Python runtime package, which includes the **pyexpat** module, does not have an appropriate versioned dependency on the expat library package against which it was built:

```
gerrit0 # PYTHONPATH=/tmp/tmp.FjayTS/usr/lib/pkg/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11/lib-dynload /tmp/pkg list -v expat
FMRI                                                                         IFO
pkg://omnios/library/expat@2.5.0-151046.0:20230428T103651Z                   i--
```

```
gerrit0 # PYTHONPATH=/tmp/tmp.FjayTS/usr/lib/pkg/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11/lib-dynload /tmp/pkg contents -m runtime/python-311 | grep 'depend.*expat'
depend fmri=library/expat type=require
```

```
gerrit0 # PYTHONPATH=/tmp/tmp.FjayTS/usr/lib/pkg/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11:/tmp/tmp.FjayTS/usr/lib/python3.11/lib-dynload /tmp/pkg update -v library/expat
            Packages to update:        1
            Services to change:        1
     Estimated space available: 11.84 GB
Estimated space to be consumed:  9.59 MB
       Create boot environment:       No
Create backup boot environment:      Yes
          Rebuild boot archive:       No

Changed packages:
omnios
  library/expat
    2.5.0-151046.0 -> 2.6.4-151046.0

Services:
  restart_fmri:
    svc:/system/update-man-index:default

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1         17/17      0.2/0.2  148k/s

PHASE                                          ITEMS
Removing old actions                           15/15
Installing new actions                         15/15
Updating modified actions                      12/12
Updating package state database                 Done
Updating package cache                           1/1
Updating image state                            Done
Creating fast lookup database                   Done
Reading search index                            Done
Updating search index                            1/1
Updating package cache                           2/2
```

```
gerrit0 # pkg list -v expat
FMRI                                                                         IFO
pkg://omnios/library/expat@2.6.4-151046.0:20241116T161801Z                   i--
```
